# Generated by Django 6.0.4 on 2026-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('餐饮', '🍜 餐饮'), ('购物', '🛍️ 购物'), ('交通', '🚗 交通'), ('娱乐', '🎮 娱乐'), ('医疗', '💊 医疗'), ('教育', '📚 教育'), ('住房', '🏠 住房'), ('其他', '📦 其他')], db_index=True, max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, verbose_name='消费日期'),
        ),
    ]
