# Generated by Django 6.0.4 on 2026-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_add_expense_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': '收支记录', 'verbose_name_plural': '收支记录'},
        ),
        migrations.AddField(
            model_name='expense',
            name='record_type',
            field=models.CharField(choices=[('expense', '支出'), ('income', '收入')], db_index=True, default='expense', max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('餐饮', '🍜 餐饮'), ('购物', '🛍️ 购物'), ('交通', '🚗 交通'), ('娱乐', '🎮 娱乐'), ('医疗', '💊 医疗'), ('教育', '📚 教育'), ('住房', '🏠 住房'), ('薪资', '💰 薪资'), ('其他', '📦 其他')], db_index=True, max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
    ]
